/*
    Gestione Soci Protezione Civile
    Copyright (C) Simeosoft di Carlo Simeone
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

package proci.gui;
import com.simeosoft.form.FormController;
import com.simeosoft.form.IFormListener;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Point;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import proci.DBHandler;

/**
 *
 * @author  simeo
 */
public class Preferenze extends java.awt.Dialog implements IFormListener {
    private static final long serialVersionUID = 6804562008543317792L;
    
    final int PRE_WIDTH = 400;
    final int PRE_HEIGHT = 400;       
    Connection conn;
    String sede = null;
    FormController fc;
    Frame parent;
    
    /** Creates new form Preferenze
     * @param parent
     * @param modal */
    public Preferenze(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        Dimension frmSize = parent.getSize();
        Point loc = parent.getLocation();
        this.setSize(PRE_WIDTH,PRE_HEIGHT);
        this.setLocation((frmSize.width - PRE_WIDTH) / 2 + loc.x, 
                        (frmSize.height - PRE_HEIGHT) / 2 + loc.y);
        try {
            conn = DBHandler.getInstance().getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select * from UTIL where UTILKEY = 'SEDE'");
            rs.next();
            sede = rs.getString("UTILDATA");
        } catch (SQLException se) {
            JOptionPane.showMessageDialog(this,"<html>ERRORE DB (2): <b>" + se + "</b>","ERRORE",
                    JOptionPane.ERROR_MESSAGE);
        }
        fc = new FormController(this,jlMessage);
        fc.addTextField(jtLocalita,"Località sede",50,true);
        fc.setString(jtLocalita,sede);
    }

    @Override
    public void changed(JComponent comp) {
        jbOk.setEnabled(true);
    }
    
    private void aggiorna() {
        try {
            Statement stmt = conn.createStatement();
            sede = fc.getString(jtLocalita);
            stmt.execute("update UTIL set UTILDATA = '" + sede + "' where UTILKEY = 'SEDE'");
            jlMessage.setText("Preferenze aggiornate.");
        } catch (SQLException se) {
            JOptionPane.showMessageDialog(this,"<html>ERRORE DB (2): <b>" + se + "</b>","ERRORE",
                    JOptionPane.ERROR_MESSAGE);
        }
        parent.setTitle("Gestione Soci Protezione Civile " + sede);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jbOk = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtLocalita = new javax.swing.JFormattedTextField();
        jlMessage = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setTitle("Preferenze");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jbOk.setMnemonic('o');
        jbOk.setText("ok");
        jbOk.setEnabled(false);
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jPanel1.add(jbOk);

        jbCancel.setMnemonic('a');
        jbCancel.setText("annulla");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jPanel1.add(jbCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("localit\u00e0 sede:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jtLocalita, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        jlMessage.setMaximumSize(new java.awt.Dimension(300, 19));
        jlMessage.setMinimumSize(new java.awt.Dimension(300, 19));
        jlMessage.setPreferredSize(new java.awt.Dimension(300, 19));
        jPanel2.add(jlMessage, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        add(jPanel2, gridBagConstraints);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        aggiorna();
    }//GEN-LAST:event_jbOkActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOk;
    private javax.swing.JLabel jlMessage;
    private javax.swing.JFormattedTextField jtLocalita;
    // End of variables declaration//GEN-END:variables
    
}
