/*
    Gestione Soci Protezione Civile
    Copyright (C) Simeosoft di Carlo Simeone
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

package proci.gui;

import java.awt.Dimension;
import java.awt.Point;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import proci.DBHandler;
import proci.App;

/**
 *
 * @author  simeo
 */
public class Statistiche extends java.awt.Dialog {
    
    final int STAT_WIDTH = 400;
    final int STAT_HEIGHT = 400;       
    
    /** Creates new form Statistiche */
    public Statistiche(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension frmSize = parent.getSize();
        Point loc = parent.getLocation();
        this.setSize(STAT_WIDTH,STAT_HEIGHT);
        this.setLocation((frmSize.width - STAT_WIDTH) / 2 + loc.x, 
                        (frmSize.height - STAT_HEIGHT) / 2 + loc.y);
        int soci = 0;
        int soci_op = 0;
        int soci_nonop = 0;
        int soci_ono = 0;
        int dot = 0;
        int inte = 0;
        int ese = 0;
        int spe = 0;
        
        try {
            Connection conn = DBHandler.getInstance().getConnection();
            Statement stmt = conn.createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);
            // potrebbe essere sostituito con un batch...
            ResultSet rs = stmt.executeQuery("select * from SOCIO");
            while (rs.next()) {
                soci++;
                if (rs.getString("SOTIPO").equals("O")) {
                    soci_op++;
                } else if (rs.getString("SOTIPO").equals("N")) {
                    soci_nonop++;
                } else {
                    soci_ono++;
                }
            }
            rs = stmt.executeQuery("select count(*) from DOTAZIONE");
            if (rs.next()) {
                dot = rs.getInt(1);
            }            
            rs = stmt.executeQuery("select count(*) from INTERVENTO");
            if (rs.next()) {
                inte = rs.getInt(1);
            }            
            rs = stmt.executeQuery("select count(*) from ESERCITAZIONE");
            if (rs.next()) {
                ese = rs.getInt(1);
            }            
            rs = stmt.executeQuery("select count(*) from SPECIALIZZAZIONE");
            if (rs.next()) {
                spe = rs.getInt(1);
            }            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(App.getInstance().getMainFrame(),e,"ERRORE!",JOptionPane.ERROR_MESSAGE);
        }             

        jepData.setEditable(false);
        jepData.setContentType("text/html");
        String text = String.format("<html><body><font face='verdana,arial' size=+1><p align='center'>" +
                "Statistiche</p></font>" +
                "<table>" +
                "<tr><td>totale soci: </td><td><font color='red'>%d</font></td>" + 
                "<tr><td>soci operativi: </td><td><font color='green'>%d</font></td>" +
                "<tr><td>soci non operativi: </td><td><font color='green'>%d</font></td>" +
                "<tr><td>soci onorari: </td><td><font color='green'>%d</font></td>" +
                "<tr><td>dotazioni: </td><td><font color='blue'>%d</font></td>" +
                "<tr><td>interventi: </td><td><font color='blue'>%d</font></td>" +
                "<tr><td>esercitazioni: </td><td><font color='blue'>%d</font></td>" + 
                "<tr><td>specializzazioni: </td><td><font color='blue'>%d</font></td>",                 
                soci, soci_op, soci_nonop, soci_ono, 
                dot, inte, ese, spe);
        jepData.setText(text);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jepData = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jbOk = new javax.swing.JButton();

        setTitle("Statistiche");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        add(jepData, java.awt.BorderLayout.CENTER);

        jbOk.setMnemonic('o');
        jbOk.setText("ok");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jPanel1.add(jbOk);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_jbOkActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistiche(new java.awt.Frame(), true).setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbOk;
    private javax.swing.JEditorPane jepData;
    // End of variables declaration//GEN-END:variables
    
}
